version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    tty: true
    # command: go run hello.g
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis:6379
      DB_HOST: db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:alpine
volumes:
  mysql_data:
  redis-data:
